### ISSUE TITLE
Find doesn't work for certain species

### ISSUE THREAD

**Issue by pmbarrett314** [SimplyBLGDev/simplyblgdev.github.io#1]
I've been using the Johto map (great tool, really helpful!), and certain Pokemon with non-alphabetical characters in their names don't show up when using the Find button. Ho-oh seems to work fine, but Farfetch'd, Mr. Mime, and Nidoran M and F do not, despite all of these definitely having locations where they show up in the games.

**Comment by SimplyBLGDev** [comment]
Should be fixed now, thanks for reporting.
